### ISSUE TITLE
 Maximum number of writer processes reached (99).

### ISSUE THREAD

**Issue by AlexProfi** [pmacct/pmacct#457]
**Description**
I use pmacct in docker
and get warn in logs
WARN ( default_amqp/amqp ): Maximum number of writer processes reached (99).
How to fix it? I cant set number more than 99 it set it to default 10

**Version**
pmacct/pmacctd:bleeding-edge

**Appreciation**

```
version: '3.3'
services:
  pmacct:
    image: pmacct/pmacctd:bleeding-edge
    container_name: pmacct
#    restart: 'unless_stopped'
    restart: 'no'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 131072
        hard: 131072
      nproc: 8192
      fsize: -1
    network_mode: host
    volumes:
#      change path according to host system
      - ./settings:/etc/pmacct
      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
    environment:
      TZ: "Europe/Moscow"
```

this is my pmacctd.conf

```
plugins: nfprobe[external], amqp
plugin_pipe_size[external]: 40960000
plugin_buffer_size[external]: 3530

#TODO for test
#plugin_pipe_size[external]: 2024000000
#plugin_buffer_size[external]: 2024000
debug: false
nfprobe_direction: out
nfprobe_receiver: mon01.11.ru:2055
nfprobe_version: 10

#TODO fix broken
aggregate:  class, src_host_country,timestamp_arrival,src_host, dst_host, src_port, dst_port, proto, peer_src_ip, tos

nfprobe_timeouts: tcp=120:maxlife=3600
snaplen: 700
pmacctd_flow_buffer_size: 4684354560
pmacctd_flow_buffer_buckets: 327680
#pmacctd_flow_lifetime: 60

#settings for send data to rabbitmq
amqp_host: mon02.11.ru
amqp_output: json
amqp_frame_max: 131072 #default
amqp_user: skit
amqp_passwd: 88KjiGfcLjvf
amqp_exchange: pmacct
amqp_persistent_msg: true
amqp_routing_key: acct
amqp_max_writers: 99
#for round robin to consumers ( num of consumers with pattern amqp_routing_key_N
#amqp_routing_key_rr: 3
amqp_refresh_time: 30
amqp_history: 1h
# settings for save timestamps in Unix TimeStamp format
timestamps_since_epoch: true
#amqp_history_roundoff: m
#wait for listen device when it will be available
#pcap_interface_wait: true

classifier_proto_guess: true
pcap_interfaces_map: /etc/pmacct/ifaces.conf

#ifaces.conf

ifindex=100 ifname=eno2 direction=in
```
