### ISSUE TITLE
[RPKI] bgp_daemon needs to be enabled to be able to connect to RTR cache

### ISSUE THREAD

**Issue by SanderDelden** [pmacct/pmacct#765]
**Description**
We are implementing insight into RPKI using PMACCT, our `sfacctd` daemon is working as intended however we are running into some problems with `nfacctd`. After some testing it seems that the `bgp_daemon` needs to be enabled in the configuration in order to connect to the RTR cache.

Example `nfacctd` configuration:
```
plugins: print[roa]

bgp_daemon: true
nfacctd_port: 5008
rpki_rtr_cache: 172.20.0.20:3323
rpki_rtr_cache_version: 0

aggregate[roa]: dst_roa
print_output_file[roa]: /tmp/pmacct/1m_roa.json
print_output[roa]: json
print_history[roa]: 1m
print_history_roundoff[roa]: m
print_refresh_time[roa]: 60
print_output_file_append[roa]: true
```

Example `docker-compose.yml`:
```
%YAML 1.1
---
version: '3.8'
services:
  nfacctd:
    image: pmacct/nfacctd:bleeding-edge
    volumes:
    - $PWD/pmacct.conf:/etc/pmacct/nfacctd.conf:ro
    networks:
      pmacct_network:
        ipv4_address: 172.20.0.10

  routinator:
    image: nlnetlabs/routinator:v0.13.2
    command: ["server", "--rtr", "0.0.0.0:3323", "--http", "0.0.0.0:8323"]
    networks:
      pmacct_network:
        ipv4_address: 172.20.0.20

networks:
  pmacct_network:
    ipam:
      config:
      - subnet: 172.20.0.0/24
```

When starting the containers we see in the logging that the RTR cache is succesfully connected:
`INFO ( default/core/RPKI ): Connected to RTR Cache: 172.20.0.20:3323`

Remove the `bgp_daemon: true` and this log entry is no longer observed.

With `sfacctd` we require the BGP daemon for AS information, however with `nfacctd` we receive this information from the IPFIX records hence we do not have a BGP session for the process. We still need to enable the `bgp_daemon` in order for the RTR cache to be used but this seems to cause  (just guessing at this point) all ROA information in the output to be set to "u" (unknown). Could the fact that no BGP neighbors are present for the `nfacctd` process cause this?

**Version**
We are running 1.7.8 but I've also tested this against the latest bleeding-edge (nfacctd 1.7.10-git (20240308-0 (29019196))) with the same results.

**Appreciation**
Please consider starring this project to boost our reach on github!
✅

If any additional information is required, please let me know.
