### ISSUE TITLE
bug: Incorrect field name in Kafka JSON: `as_apth` instead of `as_path`

### ISSUE THREAD

**Issue by Zerka30** [pmacct/pmacct#848]
Hi :wave: ,

I encountered an issue with the JSON output generated by the official Docker image `pmacct/sfacctd:latest`. The field `as_path` appears to be incorrectly labeled as `as_apth` in the Kafka output. This typo causes downstream processing issues in systems that expect the correct field name.

Example : 
```json
{
   "event_type":"purge",
   "as_dst":"REDACTED",
   "comms":[],
   "ecomms":[],
   "lcomms":[],
   "as_apth":[
      "200",
      "100"
   ],
   "local_pref":150,
   "peer_ip_dst":"REDACTED",
   "net_dst":"REDACTED",
   "mask_dst":16,
   "stamp_inserted":"2025-01-14 08:49:00",
   "stamp_updated":"2025-01-14 08:50:01",
   "packets":32000,
   "bytes":48320000,
   "writer_id":"default_kafka/3826"
}
```

**Environment Details** : 
- Docker image used: `pmacct/sfacctd:latest`
- sfacctd version : `sFlow Accounting Daemon, sfacctd 1.7.9-git [20240618-0 (a2f3eaa7)]`
- pmbgpd version : `pmacct BGP Collector Daemon, pmbgpd 1.7.9-git (20240618-0 (a2f3eaa7))`

Configuration :
```
# General
debug: false
pre_tag_map: /etc/pmacct/internet_uplinks.map
networks_file: /etc/pmacct/networks.lst
as_path_encode_as_array: true

# Aggregate rules
aggregate: dst_net, dst_mask, dst_as, as_path, std_comm, ext_comm, lrg_comm, peer_dst_ip, local_pref

# sFlow
sfacctd_ip: 0.0.0.0
sfacctd_port: 6343
sfacctd_as: longest
sfacctd_net: longest
sfacctd_renormalize: true

# BGP
bgp_daemon: true
bgp_daemon_ip: 0.0.0.0
bgp_daemon_msglog: true
bgp_daemon_max_peers: 100
bgp_agent_map: /etc/pmacct/bgp_agent.map
bgp_comms_encode_as_array: true

# Kafka
plugins: kafka
kafka_output: json
kafka_broker_host: X.X.X.X
kafka_refresh_time: 60
kafka_history: 1m
kafka_history_roundoff: m

# Memory settings
imt_mem_pools_number: 0
plugin_pipe_size: 10240000
plugin_buffer_size: 1024000
```

<details>
  <summary>docker-compose.yml</summary>

  ```yaml
  ---
  services:
    pmacct:
      image: pmacct/sfacctd:latest
      restart: always
      init: true
      network_mode: host
      privileged: true
      volumes:
        - ${PWD}/configs/pmacct:/etc/pmacct:ro
        - ${PWD}/data/pmacct:/var/lib/pmacct/:rw
      depends_on:
        - kafka

    kafka:
      image: bitnami/kafka:latest
      restart: always
      ports:
        - 9092:9092
      environment:
        KAFKA_CFG_NODE_ID: 0
        KAFKA_CFG_PROCESS_ROLES: controller,broker
        KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://X.X.X.X:9092
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
        KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      depends_on:
        zookeeper:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
        interval: 30s
        timeout: 10s
        retries: 5

    zookeeper:
      image: bitnami/zookeeper:latest
      restart: always
      ports:
        - "2181:2181"
      environment:
        ALLOW_ANONYMOUS_LOGIN: "yes"
      healthcheck:
        test: ["CMD", "zkServer.sh", "status"]
        interval: 10s
        timeout: 10s
        retries: 5
```
</details> 

**Steps to Reproduce** :

1. Run the Docker container `pmacct/sfacctd:latest` with the provided configuration.
2. Monitor the Kafka topic configured in kafka_broker_host for JSON messages.
3. Observe the field `as_apth` instead of the expected `as_path`.
